```{r fetch_and_wrangle}
library(tidyverse)
library(naniar)
library(rvest)
library(lubridate)
library(jsonlite)

url <- "https://interactive.guim.co.uk/2017/feb/09/gva-data/UCR-1985-2015.csv"

data <- url %>%
  read_csv()

comp <- data[complete.cases(data), ] %>%
  gather(... = -c(Agency, city, state, state_short)) %>%
  tidyr::extract(key, c("year", "stat_type"), "([0-9]+)_([a-z_]*)")

comp$year <- comp$year %>% as.numeric()
```

```{r fetch_and_wrangle2}
myapi <- ""
url <- "https://api.stlouisfed.org/fred"
cities <- "Houston|New York|Chicago|Detroit|Los Angeles"



# Functions for fetching data
fetch <- . %>%
  read_html() %>%
  html_text() %>%
  jsonlite::fromJSON()

fetch_series <- . %>%
  .$seriess %>%
  as_tibble()

fetch_observation <- . %>%
  .$observations %>%
  as_tibble()



# Fetch the series information
file.path(url, "release") %>%
  file.path(paste0("series?release_id=113&api_key=", myapi, "&file_type=json")) %>%
  fetch %>%
  fetch_series %>%
  filter(grepl(cities, title), grepl("Unemployment", title), grepl("NSA", seasonal_adjustment_short)) -> x



# Fetch the actual data (observation)
y <- url %>%
  file.path("series", "observations") %>%
  paste0("?series_id=", x$id, "&api_key=", myapi, "&file_type=json", "&frequency=a")

z <- y %>%
  map(fetch) %>%
  map(fetch_observation)



# Tidy data
cast_date <- . %>%
    mutate(date = as.Date(date))

add_year <- . %>%
  mutate(year = year(date))

remove_2017 <- . %>%
    filter(year != 2017)

z <- z %>%
  map(cast_date) %>%
  map(add_year) %>%
  map(remove_2017)

names(z) <- c("Detroit", "Chicago", "Houston", "Los Angeles", "New York City")



# Join data sets
m <- comp %>%
filter(grepl(cities, city)) %>%
mutate(city = factor(city, c("Detroit", "Chicago", "Houston", "Los Angeles", "New York City")))

z <- lapply(seq(z), function(x) {
    z[[x]] %>%
        dplyr::inner_join(m %>% filter(city == names(z)[x]) %>% spread(stat_type, value), by = "year")
})

z <- Reduce(function(...) dplyr::union(...), z)

z <- z %>%
  mutate(value = as.numeric(value)) %>%
  rename(unemployment_rate = value)
```


```{r plot}
cities2 <- "Houston|New York City|Chicago|Detroit|Los Angeles"
comp %>%
  filter(grepl(cities2, city)) %>%
  mutate(city = factor(city, c("Detroit", "Chicago", "Houston", "Los Angeles", "New York City"))) %>%
  ggplot(aes(as.numeric(year), unemployment_rate)) +
    geom_line(aes(color = city)) +
    facet_wrap(~stat_type, scales = "free_y")
```

```{r plot2}
p <- comp %>%
  filter(grepl(cities2, city)) %>%
  spread(stat_type, unemployment_rate) %>%
  ggplot(aes(murder_rate, raw_murder_num)) +
    geom_point() +
    geom_point(aes(color = city, frame = as.numeric(year), cumulative = TRUE), alpha = 2/3, size = 2) +
  facet_wrap(~city)

p %>% gganimate::gganimate("tst.gif")
```

```{r plot3}
p <- z %>% ggplot(aes(unemployment_rate, murder_rate)) + geom_point() + geom_point(aes(color = city, frame = year, cumulative = TRUE), size = 2, alpha = 0.80) + facet_grid(. ~ city)

animation::ani.options(interval = 0.2, height = 600, width = 800)

p %>% gganimate::gganimate("tst.gif", fps = 0.5)
```