---
title  : "Duration Of Unemployment"
author : "Luke Smith"
date   : "04-23-2017"
tags   : [r, economics, plotting]
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo =  FALSE)
knitr::opts_chunk$set(fig.height = 8)
knitr::opts_chunk$set(message    = FALSE)
knitr::opts_chunk$set(warning    = FALSE)

library(tidyverse)
library(rvest)
library(jsonlite)
library(lubridate)
library(GGally)

# Plot set up
my_red        <- "#ce1141"
my_red2       <- "#a33c56"
my_lightred   <- "#fabdcd"
my_darkred    <- "#870b2b"
my_blue       <- "#4fa8ff"
my_blue2      <- "#1141ce"
my_purple     <- "#8E3694"
my_green      <- "#008348"
my_green2     <- "#1e6545"
my_lightgreen <- "#00be68"
my_darkgreen  <- "#00371e"
my_orange     <- "#e15c39"
my_orange2    <- "#834800"

## Other series of interest:
# CLF Participation by age:
clfpr_16_19   <- "LNU01300012" # CLF Participation Rate: 16 to 19 (NSA)
clfpr_20_24   <- "LNS11300036" # CLF Participation Rate: 20 to 24 (NSA)
clfpr_25_54   <- "LNU01300060" # CLF Participation Rate: 25 to 54 (NSA)
clfpr_55_over <- "LNU01324230" # CLF Participation Rate: 55 and over (NSA)

# CLF Levels (number of people) by age
clfl         <- "CLF16OV" # CLF Level (SA)
nlfl         <- "LNS15000000" # Not in Labor Force (SA)
clfl_16_19   <- "LNS11000012" # CLF Level: 16 to 19 (SA)
clfl_20_24   <- "LNS11000036" # CLF Level: 20 to 24 (SA)
clfl_25_54   <- "LNS11000060" # CLF Level: 25 to 54 (SA)
clfl_55_over <- "LNS11024230" # CLF Level: 55 and over (SA)

# Misc 
ue_15_longer <- "U1RATE" # Unemployed 15 weeks or longer as percent of CLF (SA)

recessions <- read.table(textConnection(
"Peak, Trough
1857-06-01, 1858-12-01
1860-10-01, 1861-06-01
1865-04-01, 1867-12-01
1869-06-01, 1870-12-01
1873-10-01, 1879-03-01
1882-03-01, 1885-05-01
1887-03-01, 1888-04-01
1890-07-01, 1891-05-01
1893-01-01, 1894-06-01
1895-12-01, 1897-06-01
1899-06-01, 1900-12-01
1902-09-01, 1904-08-01
1907-05-01, 1908-06-01
1910-01-01, 1912-01-01
1913-01-01, 1914-12-01
1918-08-01, 1919-03-01
1920-01-01, 1921-07-01
1923-05-01, 1924-07-01
1926-10-01, 1927-11-01
1929-08-01, 1933-03-01
1937-05-01, 1938-06-01
1945-02-01, 1945-10-01
1948-11-01, 1949-10-01
1953-07-01, 1954-05-01
1957-08-01, 1958-04-01
1960-04-01, 1961-02-01
1969-12-01, 1970-11-01
1973-11-01, 1975-03-01
1980-01-01, 1980-07-01
1981-07-01, 1982-11-01
1990-07-01, 1991-03-01
2001-03-01, 2001-11-01
2007-12-01, 2009-06-01"), sep=',',
colClasses=c('Date', 'Date'), header=TRUE)

recessions <- as_tibble(recessions)
```




```{r import_fred_data_file, cache=TRUE}
ue_orig <- read_csv("C:/Users/Luke/Downloads/fredgraph.csv")
```

```{r import_fred_data_fred, cache=TRUE}
fred_api <- "8422d5c5396bd742cf7f64f054e290f7"
root <- "https://api.stlouisfed.org/fred"

# q_release <- "/release/series?release_id="
q_series  <- "/series/observations?series_id="
q_api <- "api_key="
# q_tags <- "tag_names="

file_type <- "file_type=json"

id_series <- c("UNRATE", "CIVPART", "UEMPMEAN", "UEMPMED")
# id_release <- 332
# tags <- "engineering"

search <- paste0(root, q_series, id_series, "&",
                 q_api, fred_api, "&",
                 file_type)

h <- search %>%
  map(read_html)

h_json <- h %>%
  map(html_text) %>%
  map(fromJSON) %>%
  map(function(x) map(x, function(y) if (is.data.frame(y) == TRUE) as_tibble(y) else y))

names(h_json) <- id_series
```




```{r wrangle_data, cache=TRUE}
obs <- h_json %>%
  map(function(x) x[["observations"]])

    obs_len <- obs %>%
      map(nrow)
```

```{r wrangle_data2, cache=TRUE}
obs_df <- obs %>%
  reduce(dplyr::union_all)

id <- seq_along(obs_len) %>%
  lapply(function(x) rep(id_series[[x]], times = obs_len[[x]])) %>%
  unlist()

obs_df <- obs_df %>%
  add_column(id = id) %>%
  select(id, date, value) %>%
  mutate(date = as.Date(date),
         value = as.numeric(value))

obs_df2 <- obs_df %>%
    spread(id, value) %>%
    mutate(decade = with(., case_when(
        year(date) < 1970 ~ "1960's",
        between(year(date), 1970, 1979) ~ "1970's",
        between(year(date), 1980, 1989) ~ "1980's",
        between(year(date), 1990, 1999) ~ "1990's",
        between(year(date), 2000, 2009) ~ "2000's",
        between(year(date), 2010, 2019) ~ "2010's"
    )))
```




```{r plot_obs_df_curves, fig.height=6}
obs_df %>%
  mutate(id = with(., case_when(
    id == "CIVPART"  ~ "Civilian Participation Rate",
    id == "UEMPMEAN" ~ "Mean Duration of Unemployment",
    id == "UEMPMED"  ~ "Median Duration of Unemployment",
    id == "UNRATE"   ~ "Civilian Unemployment Rate"))) %>%
  ggplot(aes(date, value)) +
  geom_line(aes(color = id)) +
  facet_wrap(~id, scales = "free_y") +
  guides(color = FALSE) +
  scale_color_manual(values = c(my_green, my_purple, my_red, my_darkred)) +
  theme_minimal()
```




```{r add_decade}
ue <- ue_orig %>%
  mutate(decade = with(., case_when(
    year(DATE) < 1970 ~ "1960's",
    between(year(DATE), 1970, 1979) ~ "1970's",
    between(year(DATE), 1980, 1989) ~ "1980's",
    between(year(DATE), 1990, 1999) ~ "1990's",
    between(year(DATE), 2000, 2009) ~ "2000's",
    between(year(DATE), 2010, 2019) ~ "2010's"
    )))
```




```{r plot_points_by_decade}
p <- ue %>%
  ggplot(aes(UEMPMEAN, UEMPMED)) +
    geom_point(data = ue_orig, aes(UEMPMEAN, UEMPMED), color = "gray80") +
    geom_point(aes(color = decade)) +
    facet_wrap(~decade) +
    # theme(panel.grid.major.x = element_blank(),
          # panel.grid.minor.x = element_blank()) +
    scale_y_continuous(minor_breaks = c(10, 20, 30, 40),
                       lim = c(0, 45)) +
    scale_x_continuous(minor_breaks = c(10, 20, 30, 40)) +
    labs(title = "Duration of Unemployment by Decade",
         x = "Mean Duration of Unemployment (Weeks)",
         y = "Median Duration of Unemployment (Weeks)") +
    guides(color = FALSE) +
    theme_minimal()
```

```{r plot_histogram_by_decade}
q <- ue %>%
  rename(`Mean` = UEMPMEAN, `Median` = UEMPMED) %>%
  gather(... = -c(DATE, decade)) %>%
  ggplot(aes(value)) +
  geom_histogram(data = ue_orig %>% rename(Mean = UEMPMEAN, Median = UEMPMED) %>% gather(... = -DATE), aes(value), binwidth = 2, fill = "gray80") +
  geom_histogram(aes(fill = decade), binwidth = 2) +
  facet_grid(decade ~ key) +
  labs(title = "Duration of Unemployment
by Type and Decade",
       x = "Duration of Unemployment (Weeks)",
       y = "Number of Months") +
  # scale_fill_discrete(name = "Decade") +
  guides(fill = FALSE) +
  scale_y_continuous(minor_breaks = c(0, 50, 100, 150, 200),
                     lim = c(0, 250)) +
  scale_x_continuous(minor_breaks = c(10, 20, 30, 40)) +
  theme_minimal()
```

```{r plot_lm_by_decade}
r <- ue %>%
  ggplot(aes(UEMPMEAN, UEMPMED)) +
    geom_smooth(data    = ue_orig,
                mapping = aes(UEMPMEAN, UEMPMED),
                color   = "gray80",
                method  = "lm") +
    geom_smooth(mapping = aes(color = decade),
                method  = "lm",
                se      = FALSE) +
    facet_wrap(~decade) +
    guides(color = FALSE) +
    scale_y_continuous(minor_breaks = c(10, 20, 30, 40),
                       lim = c(0, 45)) +
    scale_x_continuous(minor_breaks = c(10, 20, 30, 40)) +
    theme_minimal()
```

```{r plot_mesh, fig.height=6}
gridExtra::grid.arrange(p, q, ncol = 2)
```




```{r plot_scatmat, eval=FALSE}
obs_df %>%
  spread(id, value) %>%
  keep(is.numeric) %>%
  data.frame() %>%
  scatmat() +
  theme_minimal()
```




```{r plot_point_UNRATE_CIVPART, eval=FALSE}
obs_df2 %>%
    ggplot(aes(UNRATE, CIVPART)) +
    geom_point(data    = obs_df %>% spread(id, value),
               mapping = aes(UNRATE, CIVPART),
               color   = "gray80") +
    geom_point(aes(color = decade)) +
    facet_wrap(~decade) +
    theme_minimal()
```

```{r plot_point_UEMPMEAN_CIVPART, eval=FALSE}
obs_df2 %>%
  ggplot(aes(UEMPMEAN, CIVPART)) +
  geom_point(data    = obs_df %>% spread(id, value),
             mapping = aes(UEMPMEAN, CIVPART),
             color   = "gray80") +
  geom_point(aes(color = decade)) +
  facet_wrap(~decade) +
    theme_minimal()
```




```{r plot_line_CIVPART_color_UEMPMEAN, fig.height=5.5}
obs_df2 %>%
  ggplot(aes(date, CIVPART)) +
  geom_line(aes(color = UEMPMEAN), size = 1.0) +
  scale_color_continuous(low = my_blue,
                         high = my_orange,
                         name = "Mean Duration of
Unemployment (Weeks)") +
  scale_x_date(minor_breaks = as.Date(c("1960-01-01", "1980-01-01",
                                        "2000-01-01", "2020-01-01"))) +
  scale_y_continuous(minor_breaks = c(60, 62.5, 65, 67.5)) +
  labs(title = "Civilian Labor Force Participation Rate",
       x     = "Date",
       y     = "Civilian Participation Rate (%)") +
  theme_minimal()
```