---
title       : "Lahman Database: Oldest and Youngest Debuts"
author      : "Luke Smith"
date        : "03/24/2017"
description : "An exploration into the oldest and youngest players to make an MLB debut, by birth year and debut year."
tags        : [r, lahman, baseball]
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



Inspiration drawn from: http://seanlahman.com/baseball-archive/youngest-active-player-chronology/



```{r r_setup, message=FALSE}
library(Lahman)
library(lubridate)
library(tidyverse)
library(forcats)
library(naniar)

# Find missing birth information
missing_birth <- Master %>%
  select(starts_with("birth")) %>%
  miss_var_summary()

missing_birth

# Filter out NA's in 'birthDate'
Master2 <- Master %>%
  filter(!is.na(birthDate), !is.na(debut)) %>%
  mutate(debut = as.Date(debut),
         debut_year = year(debut),
         debut_age = debut - birthDate)
```


```{r incorrect_birthDate}
# Lefty Johnson's birthDate is wrong
Master %>%
  filter(playerID=="johnsbi01") %>%
  select(playerID, nameFirst, nameLast, birthDate, debut) %>%
  mutate(debut_age = as.Date(debut) - as.Date(birthDate))

# Take a look at the Lahman database
#   imported from Sean Lahman's MySQL
#   import script.
library(RMySQL)
db <- dbConnect(MySQL(), dbname = "lahman", user = "root", password = "0rac1e")
Master_MySQL <- dbGetQuery(db, "SELECT * FROM Master;") %>% as_tibble()

df <- dbGetQuery(db, "SELECT playerID, STR_TO_DATE(CONCAT(birthYear, '-', birthMonth, '-', birthDay), '%Y-%m-%d') as birthDate, debut
                 FROM Master
                 WHERE birthDay IS NOT NULL AND birthMonth IS NOT NULL AND birthYear IS NOT NULL AND debut IS NOT NULL
                 GROUP BY YEAR(debut)
                 ORDER BY debut;") %>% as_tibble()

# Also, 1121 records in R Lahman package
#   that are not present in Sean Lahman's
#   database (MySQL script).
Master %>%
  anti_join(Master_MySQL, by = "playerID") %>%
  select(1:2, 5, 14, 15, 21) %>%
  as_tibble()

# There are also no records in the MySQL
#   database that do not appear in the
#   R Lahman package.
Master_MySQL %>% anti_join(Master, by = "playerID")
```




```{r youngest_by_debut}
# Work in progress.
# Need to substract birthDate from debut
#  in order to find the actual oldest and
#  youngest players.

# youngest_by_debut <- Master2 %>%
#   group_by(debut_year = year(debut)) %>%
#   arrange(debut_age) %>%
#   filter(row_number() == 1) %>%
#   ungroup()

youngest_by_debut <- Master2 %>%
  group_by(debut_year = year(debut)) %>%
  filter(debut_age == min(debut_age)) %>%
  ungroup()

# youngest_by_debut <- Master2 %>%
#   group_by(debut_year = year(debut)) %>%
#   summarize(debut_age_min = min(debut_age)) %>%
#   ungroup() %>% {
#     tmp <- .
#     Master2 %>%
#       mutate(debut_year = year(debut)) %>%
#       semi_join(tmp, by = c("debut_age" = "debut_age_min", "debut_year"))
# 
# } %>% select(playerID, nameFirst, nameLast, birthDate, debut) %>%
#   arrange(debut) %>%
#   unite(Player, nameFirst, nameLast, sep = " ")
# 

youngest_by_debut %>%
  arrange(desc(debut)) %>%
  select(playerID, nameFirst, nameLast, birthCountry, birthDate, debut)
```

```{r ybd_plot, fig.width=9}
youngest_by_debut %>%
  ggplot(aes(year(debut), birthCountry)) +
    geom_count() +
    coord_flip()

```



```{r birthCountry_counts, fig.height=9}
# Master %>%
#   count(birthCountry) %>%
#   arrange(desc(n)) %>%
#   print(n = Inf)

Master %>%
  mutate(birthCountry = if_else(is.na(birthCountry), "NA", birthCountry)) %>%
  ggplot(aes(reorder(birthCountry, birthDate, length))) +
    geom_bar() +
    xlab("Number of Players") +
    ylab("Birth Country") +
    coord_flip()
```


`r Master %>% filter(birthCountry == "At Sea") %>% unite(Player, nameFirst, nameLast, sep = " ") %>% select(Player, birthYear) %>% {paste(.$Player, "in", .$birthYear)}`



```{r earliest_birthCountry_debut}
Master2 %>%
  filter(!is.na(debut)) %>%
  group_by(birthCountry) %>%
  summarise(earliest_appearance = min(debut)) %>%
  arrange(earliest_appearance) %>%
  print(n = Inf)
```


```{r debut_by_birthCountry}

debut_country_counts <- Master %>%
  count(birthCountry)

debut <- . %>% 
  filter_(debut_country_counts, .) %>%
  semi_join(Master, ., by = "birthCountry")

# More than 100
debut_by_birthCountry <- debut("n > 1") %>%
  ggplot(aes(year(debut))) +
  geom_density(aes(y = ..count.., fill = fct_rev(fct_reorder(birthCountry, birthCountry, length))), position = "stack", alpha = 3/4) +
    ggExtra::rotateTextX(45)

debut_by_birthCountry2 <- debut("n > 1") %>%
  ggplot(aes(year(debut))) +
  # geom_bar(aes(fill = fct_rev(fct_reorder(birthCountry, birthCountry, length))), position = "fill", width = 1) +
    geom_histogram(aes(fill = fct_rev(fct_reorder(birthCountry, birthCountry, length))), binwidth = 5)
    ggExtra::rotateTextX(45)

debut_by_birthCountry
debut_by_birthCountry2
debut_by_birthCountry %+% debut("n > 250")
debut_by_birthCountry2 %+% debut("n > 250")
debut_by_birthCountry %+% debut("dplyr::between(n, 51, 250)")
debut_by_birthCountry2 %+% debut("dplyr::between(n, 51, 250)")
debut_by_birthCountry %+% debut("dplyr::between(n, 11, 50)")
debut_by_birthCountry2 %+% debut("dplyr::between(n, 11, 50)")
debut_by_birthCountry %+% debut("n <= 10")
debut_by_birthCountry2 %+% debut("n <= 10")

```