---
title: "Looking at North Dakota Bakken Horizontal Well Production Data With R"
date: "03-01-2017"
author: "Luke Smith"
description: "A simple look at ND Bakken production data from horizontal wells."
tags: [r, analysis, oil and gas, bakken, north dakota]
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Here is my quick look at 

# Looking at the data

# Getting the data
The DMR updates their stats about once a month, so I use the following script to scrape the data on the 20th of each month (as a scheduled Window's task). The data is accessed via API queries, You can access the `counties` tibble and the `parse_API()` function via the `dput()` and `body()` call below the script, respectively.




```{r get_data, include=FALSE}
knitr::read_chunk("~/R/misc/oil/North_Dakota/data_production.R")
```




```{r get_production_data, eval=FALSE}

```




```{r get_counties, include=FALSE}
counties <- readr::read_csv("~/R/misc/oil/North_Dakota/counties.csv")
```




```{r show_counties, comment=""}
# Structure of the counties tibble
dput(counties)
```




```{r show_parse_API, comment=""}
# Body of the parse_API() function
body(seasmith::parse_API)
```


```{r production_treemap}
# http://flowingdata.com/2010/02/11/an-easy-way-to-make-a-treemap/
prod %>%
  group_by(.id, County) %>%
  summarise(Oil = sum(Cum_Oil)) %>% {
    
    map.market(.$`.id`, .$Oil, .$County, .$Oil)
    
    }
```