---
title       : "Top 25 Highest Scoring Community Owned R Questions on StackOverflow"
author      : "Luke Smith"
date        : "12-01-2016"
description : "Delving into https://data.stackexchange.com for the best of R on StackOverflow."
tags        : [r, stackoverflow]
---

___

## Intro
I have again taken advantage of [StackExchange's datawarehouse](http://data.stackexchange.com), this time to find the highest scoring community owned R questions on StackOverflow. These must be significantly important questions if they are community owned, right?

## The query
Unfortunately, I do not have the ability to make a connection to the StackExchange datawarehouse, but I can still show you the SQL statement which I used, and pretend to grab the data with the query (I actually downloaded the CSV, see next section).

```sql
SELECT TOP 25 p.Id, p.CreationDate, p.CommunityOwnedDate,
p.Title, p.Tags, p.Score, p.ViewCount, p.AnswerCount,
p.CommentCount, p.FavoriteCount
FROM Posts as p
INNER JOIN PostTags as pt ON p.Id = pt.PostId
INNER JOIN Tags as t ON t.Id = pt.TagId
INNER JOIN PostHistory as ph ON ph.PostId = p.Id
where t.TagName = 'r' AND ph.PostHistoryTypeId = 16 AND p.PostTypeId = 1
ORDER BY p.score desc
```

## The data
With that data, I can paste together links to the questions themselves, which have the general syntax `https://stackoverflow.com/questions/<PostId>`. Many of the top questions are broad meta-type discussion (i.e. R one-liners, which IDE to use, useful helper functions that don't fit into a package, etc).

```{r top25}
top25 <- read.csv("~/R/seasmith.github.io/posts/reference/top25_community_owned.csv", stringsAsFactors = FALSE)
base <- "https://stackoverflow.com/questions/"
top25$Title <- paste0("[", top25$Title, "](", base, top25$Id, ")")
knitr::kable(top25[, c(4, 6:7)])
```

