---
title  : "U.S. Oil Field Production"
author : "Luke Smith"
date   : "04-30-2017"
tags   : [r, oil and gas, economics, plotting]
---

```{r setup_std, include=FALSE}
# source("setup_std.R")

# ---- Library_Tidyverse_Setup
library(plyr)
library(tidyverse)
library(lubridate)
library(forcats)
library(stringi)

# ---- Library_ploting_Setup
library(gridExtra)
library(ggExtra)
library(GGally)
library(ggalt)
library(scales)

# ---- Library_Web_Setup
library(rvest)
library(jsonlite)

# ---- Library_Reporting_Setup
library(knitr)
library(kableExtra)



# ---- Opts_Setup
knitr::opts_chunk$set(echo =  FALSE)
knitr::opts_chunk$set(fig.height = 7)
knitr::opts_chunk$set(message    = FALSE)
knitr::opts_chunk$set(warning    = FALSE)



# ---- Options_Setup
old_scipen <- getOption("scipen")
options(scipen = 100)



# ---- Hooks_Setup
knit_hooks$set(inline = function(x) {
  if (is.numeric(x) | is.integer(x)) return(formatC(x, format = "d", big.mark = ",")) else
    if (is.character(x)) return(stringr::str_to_title(x)) else
      return(x)
})
old_inline <- knit_hooks$get("inline")
old_plot   <- knit_hooks$get("plot")



# ---- Inline_Function_Setup
# Provide a default value for a given condition
il_condition_default <- function(x, cond, ret) {
  
  if (eval(substitute(cond)) == TRUE) return(ret) else return(x)
  
}

# Rearrange the numeric base
il_num_base <- function(x, current_base = 0, new_base = 0) {
  
  new_power <- current_base - new_base
  
  return(x * 10^new_power)
  
}



# ---- Extra_Function_Setup
source_value <- function(file) {
  stopifnot(file.exists(file))
  value <- source(file, echo = FALSE)
  value <- value["value"][[1]]
}



# ---- Color_Setup
# Plot set up
my_red        <- "#ce1141"
my_red2       <- "#a33c56"
my_lightred   <- "#fabdcd"
my_darkred    <- "#870b2b"
my_blue       <- "#4fa8ff"
my_blue2      <- "#1141ce"
my_purple     <- "#8E3694"
my_green      <- "#008348"
my_green2     <- "#1e6545"
my_lightgreen <- "#00be68"
my_darkgreen  <- "#00371e"
my_orange     <- "#e15c39"
my_orange2    <- "#834800"


# ---- Recession_Setup
recessions <- read.table(textConnection(
  "Peak, Trough
  1857-06-01, 1858-12-01
  1860-10-01, 1861-06-01
  1865-04-01, 1867-12-01
  1869-06-01, 1870-12-01
  1873-10-01, 1879-03-01
  1882-03-01, 1885-05-01
  1887-03-01, 1888-04-01
  1890-07-01, 1891-05-01
  1893-01-01, 1894-06-01
  1895-12-01, 1897-06-01
  1899-06-01, 1900-12-01
  1902-09-01, 1904-08-01
  1907-05-01, 1908-06-01
  1910-01-01, 1912-01-01
  1913-01-01, 1914-12-01
  1918-08-01, 1919-03-01
  1920-01-01, 1921-07-01
  1923-05-01, 1924-07-01
  1926-10-01, 1927-11-01
  1929-08-01, 1933-03-01
  1937-05-01, 1938-06-01
  1945-02-01, 1945-10-01
  1948-11-01, 1949-10-01
  1953-07-01, 1954-05-01
  1957-08-01, 1958-04-01
  1960-04-01, 1961-02-01
  1969-12-01, 1970-11-01
  1973-11-01, 1975-03-01
  1980-01-01, 1980-07-01
  1981-07-01, 1982-11-01
  1990-07-01, 1991-03-01
  2001-03-01, 2001-11-01
  2007-12-01, 2009-06-01"), sep=',',
  colClasses=c('Date', 'Date'), header=TRUE)

recessions <- as_tibble(recessions)

```


```{r setup_api_eia, include=FALSE, cache=TRUE}
root          <- "http://api.eia.gov"
root_category <- "/category"
root_series   <- "/series"

q_api      <- "/?api_key="
q_category <- "&category_id="
q_series   <- "&series_id="
```

```{r setup_api_key_eia, include=FALSE}
api_key <- source_value("api_key_eia.R")
```

```{r import_category_296686, include=FALSE}
id_category <- 296686

q_category_296686 <- paste0(root, root_category,
                            q_api, api_key,
                            q_category, id_category)

h <- q_category_296686 %>% read_html()

cat <- h %>%
  html_text() %>%
  fromJSON() %>%
  .$category

meta <- cat$childseries %>%
  as_tibble() %>%
  filter(!grepl("PADD", name)) %>%
  filter(f == "M", units == "Thousand Barrels per Day")
```

```{r import_series, include=FALSE}
q_series_data <- paste0(root, root_series,
                        q_api, api_key,
                        q_series, meta$series_id)

h2 <- q_series_data %>% map(read_html)

proto_prod <- h2 %>% map(html_text) %>% map(fromJSON)
names(proto_prod) <- meta$series_id

prod <- proto_prod %>%
  map(function(x) as_tibble(x$series$data[[1]])) %>%
  map(function(x) {
    x <- mutate(x, V1 = paste0(V1, "01"))
    mutate(x,
           V1 = as.Date(V1, format = "%Y%m%d"),
           V2 = as.numeric(V2))
    })

names(prod) <- proto_prod %>% map(function(x) x$series$name)
ex <- names(prod)[c(1, 4, 30)] %>%
  stri_replace("", regex = " Field Production .*")

prod <- prod %>%
  plyr::ldply() %>%
  as_tibble() %>%
  dplyr::rename(date = V1,
         production  = V2,
         region      = .id)

prod <- prod %>%
  mutate(region = stri_replace(region,
                               "",
                               regex = "Field Production .*")) %>%
  mutate(region = stri_trim(region)) %>%
  mutate(state = state.abb[match(region, state.name)]) %>%
  mutate(production = production * 1000)

prod2 <- prod %>%
  filter(!grepl(paste(ex, collapse = "|"), region)) #%>%
  # filter(!grepl("U\\.S\\.", region))
```

```{r aggregate_data, include=FALSE}
# From "U.S. Refinery Imports From Saudi Arabia" post
load("all.RData")

prod2_year <- prod2 %>%
  group_by(region, state, year = year(date)) %>%
  summarize(production = (sum(production * days_in_month(date))) / sum(days_in_month(date))) %>%
  ungroup()

prod_imp <- prod2_year %>%
  left_join(all, by = c("state" = "state", "year" = "year")) %>%
  filter(between(year, 2009, 2016)) %>%
  select(region:state, imports, origin, everything())
```

```{r plot_misc}
prod2 %>%
  ggplot(aes(date, production)) +
  geom_line(aes(color = region)) +
  facet_wrap(~fct_rev(reorder(region, production, mean))) +
  guides(color = FALSE) +
  theme_minimal()
```

```{r fig.height=30, fig.width=5}
prod_imp %>%
  group_by(region, year) %>%
  summarize(imports    = sum(imports),
            production = mean(production)) %>%
  gather(... = c(imports, production)) %>%
  mutate(imports = if_else(key == "imports", value, 0)) %>%
  ggplot(aes(year, value)) +
  geom_line(aes(color = key)) +
  facet_grid(fct_rev(reorder(region,
                              imports,
                              sum, na.rm = TRUE)) ~
             key,
             scales = "free_y") +
  guides(color = FALSE)
```

```{r fig.height=20, fig.width=6}
prod_imp %>%
  group_by(region, year) %>%
  summarize(imports    = sum(imports),
            production = mean(production)) %>%
  ggplot(aes(production, imports)) +
  geom_point(aes(color = factor(year))) +
  geom_path() +
  scale_color_manual(values = c(my_lightred,
                                my_lightgreen,
                                my_orange,
                                my_blue,
                                my_purple,
                                my_green,
                                my_red,
                                "black")) +
  facet_wrap(~fct_rev(reorder(region,
                              imports,
                              sum, na.rm = TRUE)),
             scales = "free",
             ncol   = 2)
```

```{r, fig.height=30}
prod_imp %>%
    filter(!is.na(imports)) %>%
    group_by(region, year) %>%
    summarize(production = mean(production),
              imports    = sum(imports)) %>%
    ungroup() %>%
    mutate(region_year = paste0(region, "_", year)) %>%
    ggplot() +
    geom_dumbbell(aes(x    = production,
                      xend = imports,
                      y    = reorder(region_year,
                                  imports,
                                  sum,
                                  na.rm = TRUE),
                      color = production > imports),
                  colour_x = my_green,
                  colour_xend = my_red) +
  scale_color_manual(values = c(my_red, my_green))

prod_imp %>%
    filter(!is.na(imports)) %>%
    group_by(region, year) %>%
    summarize(production = mean(production),
              imports    = sum(imports)) %>%
    ungroup() %>%
    mutate(region_year = paste(region, year),
           diff = production - imports) %>%
    ggplot(aes(region_year, diff)) +
    geom_col(aes(fill = factor(sign(diff)))) +
    geom_smooth(aes(group = region), method = "glm", se = FALSE) +
    scale_fill_manual(values = c(my_red, my_green)) +
    coord_flip()

prod_imp %>%
    filter(!is.na(imports)) %>%
    group_by(region, year) %>%
    summarize(production = mean(production),
              imports    = sum(imports)) %>%
    ungroup() %>%
    mutate(region_year = paste(region, year),
           diff = production - imports) %>%
    group_by(region) %>%
    mutate(cum_production = sum(production),
           cum_imports = sum(imports),
           cum_diff = sum(diff)) %>%
    ungroup() %>%
    ggplot(aes(reorder(region_year, cum_diff, mean), diff)) +
    geom_col(aes(fill = factor(sign(diff)))) +
    geom_smooth(aes(group = region),
                method    = "glm",
                se        = FALSE) +
  scale_fill_manual(values = c(my_red, my_green)) +
    coord_flip()
```