---
title: "What is the tidyverse"
author: "Luke Smith"
date: "03-15-2017"
description: "A short primer on the tidyverse."
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## What is the tidyverse
### Philosophy
Hadley's tidy philosophy is best summed up from his [Tidy Data](http://vita.had.co.nz/papers/tidy-data.pdf) article in the Journal of Statistical Software:

* Each variable is a column
* Each observation is a row
* Each type of observational unit is a table

It sounds simple enough. It probably also sounds familiar: it is a rephrasing of Codd's [3rd normal form][3nf] with (in my opinion) better language and a clear focus on just a single dataset (rather than related datasets).

[3nf]: https://en.wikipedia.org/wiki/Third_normal_form

#### Expression
Since R is geared toward working with data, thinking about data problems with R has the advantage over other programming languages in that it helps you to express that problem.

With tidy data, meaningful function names, consistent argument order, and separation of packages by functionality, the tidyverse enhances your expression of problems with R. This gives you an advantage when solving these problems.



